spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/egarcia2506/argocd-autopilot-testing
    targetRevision: HEAD
  project: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true